name: flutter_laravel_echo
description: Port of official Laravel Echo package for your Flutter apps.
version: 0.3.0
homepage: https://github.com/nhancv/flutter_laravel_echo

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
